In [1]:
import numpy as np

In [32]:
layer1 =   np.matrix(np.random.random(size=(10,4)))

In [33]:
layer1

matrix([[0.47564726, 0.52326888, 0.63429522, 0.66787872],
        [0.08587433, 0.36110846, 0.44231884, 0.17920498],
        [0.82206121, 0.65376042, 0.09094761, 0.8415213 ],
        [0.89585323, 0.01197268, 0.66097068, 0.91920632],
        [0.8707127 , 0.75630832, 0.22423859, 0.71061574],
        [0.77479632, 0.9524719 , 0.67353072, 0.03049752],
        [0.87138764, 0.22200221, 0.70261274, 0.90758869],
        [0.64422689, 0.64001457, 0.35706591, 0.46388925],
        [0.13405795, 0.94341603, 0.64988902, 0.12378658],
        [0.21896271, 0.44208584, 0.38478633, 0.10705184]])

In [34]:
layer2 = np.matrix(np.random.random(size=(4,4)))

In [35]:
layer2

matrix([[0.82579209, 0.17440679, 0.10670771, 0.29289178],
        [0.44843405, 0.381912  , 0.99450997, 0.14982831],
        [0.01541649, 0.02140742, 0.24844297, 0.22793185],
        [0.46797715, 0.773716  , 0.417254  , 0.77883512]])

In [36]:
layer3 = np.matrix(np.random.random(size=(1,)))

In [37]:
layer3

matrix([[0.64052298]])

In [41]:
data1 = np.matrix(np.random.random(10,))

In [45]:
data1

matrix([[0.29894957, 0.70989593, 0.77580828, 0.17717477, 0.77603942,
         0.24192506, 0.15832385, 0.03416477, 0.53221074, 0.49895611]])

In [49]:
### Passing data1 through layer1

print(data1.shape,layer1.shape)
res1 = data1 @ layer1
res1

(1, 10) (10, 4)


matrix([[2.20336206, 2.51913809, 1.68955864, 1.98027857]])

In [51]:
## adding bias of 1 in this layer
res1 +=1
print(res1.shape)
res1


(1, 4)


matrix([[4.20336206, 4.51913809, 3.68955864, 3.98027857]])

In [59]:
### Passing data in layer 2
print(res1.shape,layer2.shape)
res2 = res1 @ layer2
res2

(1, 4) (4, 4)


matrix([[7.417198  , 5.61759707, 7.52029108, 5.84917363]])

In [60]:
## adding bias of 1 in this layer
res2 +=1
print(res2.shape)
res2

(1, 4)


matrix([[8.417198  , 6.61759707, 8.52029108, 6.84917363]])

In [62]:
### passing data in final layer
print(res2.shape,layer3.shape)
print(res2.T.shape,layer3.shape)
res3 = res2.T @ layer3
res3


(1, 4) (1, 1)
(4, 1) (1, 1)


matrix([[5.39140876],
        [4.23872301],
        [5.45744225],
        [4.38705312]])